package in.jaikish.kaboo.progress;

public enum GameCommands {
	GAME_BEGINS_REVEAL_TOP_CARD_FROM_DECK,
	PLAYER_THROWS_OWN_MATCHING_CARD,
	PLAYER_PICKS_CARD_FROM_DECK,
	PLAYER_SWAPS_AFTER_PICK,
	PLAYER_THROWS_BACK_PICKED_CARD,
	PLAYER_THROWS_OTHER_PLAYER_MATCHING_CARD,
	PLAYER_WANTS_TO_KNOW_OWN_CARD,
	PLAYER_WANTS_TO_KNOW_OTHER_PLAYERS_CARD,
	PLAYER_WANTS_TO_DO_A_BLIND_SWITCH,
	PLAYER_WANTS_TO_DO_A_SEE_AND_SWITCH,
	PLAYER_IS_PENALISED_FOR_WRONG_ACTION,
	PLAYER_SAYS_KABOO,
	GAME_ROUNDS_END,
	DECLARE_WINNERS
}
